### ISSUE TITLE
Define a clear versioning mechanism

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/snark-artifacts#14]
**Description**

Artifacts packages could have the same version as their circuit packages.

For example, if `@zk-kit/poseidon-proof.circom` has version `1.0.0-beta`, the `@zk-kit/poseidon-artifacts` package will have the same version `1.0.0-beta`.

Additionally, a NPM field for specifying the circuit package could be added to the `package.json` files.

After discussing and defining a strategy here, a set of rules can be added to a separate section of the README file.

**Comment by sripwoud** [comment]
- **snark artifacts generated with a fake ceremony should always be beta versions**: :heavy_check_mark:  definitely
- *Artifacts packages could have the same major/minor version as proof packages*
  Ideally I think the artifacts pkg version should match what we have here instead https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/circuits/circom? in the `-proof` package we have only js/ts code that hasn't to do directly with the snark artifacts. What matters more is the relationship between the circom files and the corresponding zkey, wasm files.
  But the individual circom circuits aren't versioned, only the higher @zk-kit/circuits pkg is versioned correct? Would it be ok to have so many packages?
    - `@zk-kit/eddsa-circom`: version always match `@zk-kit/eddsa-artifacts`
    - `@zk-kit/eddsa-artifacts`: version always match `@zk-kit/eddsa-circom`
    - `@zk-kit/eddsa-proof`: no need to match `@zk-kit/eddsa-artifacts` or `@zk-kit/eddsa-circom`

**Comment by sripwoud** [comment]
Decision: 
We will just keep track of the relationship between the `@zk-kit/circuits` package and the `@zk-kit/*-artifacts` version via commit references in the CHANGELOG.md files of the `@zk-kit/*-artifacts` packages.

**Comment by sripwoud** [comment]
TODO:
- [ ] add it to [OVERVIEW.md](https://github.com/privacy-scaling-explorations/snark-artifacts/blob/main/OVERVIEW.md)
- [ ] update the CHANGELOG.md of already published packaged

**Comment by sripwoud** [comment]
> Decision: 
> 
> We will just keep track of the relationship between the `@zk-kit/circuits` package and the `@zk-kit/*-artifacts` packages versions via commit references in the CHANGELOG.md files of the `@zk-kit/*-artifacts` packages.

@cedoor given the creation of

https://github.com/privacy-[](https://github.com/privacy-scaling-explorations/zk-kit.circom)scaling-explorations/zk-kit.circom

I think we should reconsider this decision.
shouldnt we keep
@zk-kit/artifacts and @zk-kit.circom in sync?

**Comment by cedoor** [comment]
@sripwoud Maybe an approach like: if there's a specific package for a circuit the artifacts keep the same version, otherwise, for all the other cases, the option we discussed (commit references) should be fine. How does it sound?

**Comment by sripwoud** [comment]
Sounds good.
"for all the other cases": just for clarity, here we are especially talking about those artifacts which would exist only in `@zk-kit/artifacts` and not in any other `@zk-kit` packages right? Like we would reference a commit of a circuit that is not packaged.

**Comment by sripwoud** [comment]
The semaphore circuits are a situation I hadn't really thought about.
It does not exist in any `@zk-kit` packages. But there exist  packaged circuits for it, just in another org (`@semaphore-protocol`).

So the decision criteria and rules could be:
Let `proof` the name we'll use to refer to that family of circuits inside the `snark-artifacts` repo.

- Are the circom circuits corresponding to the `proof` artifacts managed in the `snark-artifacts` repo packaged? (we've been using npm but it does not have to be npm, what we need is only a clear version number to follow)
  - **yes**:
    let `PKG` be that 3rd party package, then  
    - **the version number in `@zk-kit/{proof}-artifacts` must be in sync with `PKG`**.  
    - **`PKG` must be mentioned in the description field of `proof` package.json**.
    - Practically (dx/tooling), here we must not use the `changeset` CLI to bump the version as we will pin/track the versions manually
  - **no**:   
  the circuits must still be version controlled somewhere in a remote repository (we require it in the Pull Request template).  
  Let's call `sha` the commit where the relevant circuits were published in the remote repository `repo`.   
    - **Each new release of `@zk-kit/{proof}-artifacts` must include a reference to `sha` in its `CHANGELOG.md`.**
    - **`repo` must be mentioned in the description field of the `proof` package.json**
    - Practically (dx/tooling) here we will use the `changeset` CLI.

**Comment by cedoor** [comment]
@sripwoud We could also add a custom NPM field for the circuit reference, which could contain a NPM package with its version or a commit reference. What do you think?

The Semaphore package is different from the other ZK-Kit packages tho. A new version of `@semaphore-protocol/circuits` could be released without there necessarily being a change in the circuits. In those cases the artifacts don't need to be updated.

**Comment by cedoor** [comment]
> Like we would reference a commit of a circuit that is not packaged.

Yes 👍🏽

**Comment by sripwoud** [comment]
> A new version of @semaphore-protocol/circuits could be released without there necessarily being a change in the circuits. In those cases, the artifacts don't need to be updated


I see.
the rule "versions must be in sync (at all time) is indeed too strict then.
What I d like to follow is "if a circuits package exists, the artifacts pkg version should match the version of the circuits package that contains the circom files the artifacts were built from"

**Comment by cedoor** [comment]
> What I d like to follow is "if a circuits package exists, the artifacts pkg version should match the version of the circuits package that contains the circom files the artifacts were built from"

Sounds great! If we have a deal we can update the *.md files with this information I guess.

**Comment by sripwoud** [comment]
Closed by #59
