### ISSUE TITLE
chore: remove changeset

### ISSUE THREAD

**Issue by sripwoud** [privacy-scaling-explorations/snark-artifacts#36]
- [ ] Remove changeset CLI dev dep
- [ ] remove changeset repo bot
- [ ] use something else to automate releasing and publishing packages

_see https://github.com/privacy-scaling-explorations/snark-artifacts/pull/31#discussion_r1598976958_

**Comment by cedoor** [comment]
We could use a simple CI workflow to release all versions that have not been released yet. Like https://github.com/privacy-scaling-explorations/zk-kit.circom/blob/3829c5ae54a69c6220aba223c950451327a21ae5/.github/workflows/release.yml#L36

**Comment by sripwoud** [comment]
changeset actually supports pre release
https://github.com/changesets/changesets/blob/main/docs/prereleases.md

So I think I'd like to keep it.
I think I prefer changeset over the yarn scripts that exist in `zk-kit` or `semaphore` repos :sweat_smile: because
- the CLI is interactive (you can't pick a wrong package, unlike with `yarn version:bump`)
- it is more automated: the ci edit the package.json to bump versions automatically then creates a PR I just have to review.
- I like having a CHANGELOG.md

But I do like the formatting of your release notes you get with https://github.com/privacy-scaling-explorations/zk-kit/blob/main/.yarn/patches/changelogithub-npm-0.13.3-1783949906.patch
I like seeing the author of the PRs.
I'll see if there is a way to tweak the format of the release notes with `changeset` too

**Comment by sripwoud** [comment]
Replaced by #62
