### ISSUE TITLE
  feat(utils): use multiple sources to download snark artifacts

### ISSUE THREAD

**Issue by sripwoud** [privacy-scaling-explorations/snark-artifacts#65]
I don't really know why we see bad gateway errors in the ci when attempting to fetch the artifacts.
https://github.com/privacy-scaling-explorations/zk-kit/actions/runs/8837164770/job/24265411154#step:9:666

As an improvement (hopefully fix), I am thinking about a retry mechanism:
- use `[[unpkgCdn, jsdelivrCdn], github]` urls list
- randomly sort the cdns part
- try the next one if the 1st cdn tried failed
- repeat
- the ultimate fallback would be the snark artifacts github repo raw url. We can leverage the release tags urls, ex: https://github.com/privacy-scaling-explorations/snark-artifacts/tree/@zk-kit/semaphore-artifacts@1.0.0/packages/eddsa
Luckily the url structure on github also matches what [unpkg](https://unpkg.com/) and [jsdelivr](https://www.jsdelivr.com/) use.

The random sorting would happen on each download attempts (whether it is for a a different proof, or different artifact for a same proof...), which should protect us against throttling (if that is the root cause of the bad gateway issues...)

**Comment by sripwoud** [comment]
@artwyman Just pinging you directly to bring your attention on the latest change we've done.
We now use a single private CDN (s3 bucket + cloudfront) to serve all our artifacts.
See https://github.com/privacy-scaling-explorations/snark-artifacts/pull/91

**Comment by artwyman** [comment]
> @artwyman Just pinging you directly to bring your attention on the latest change we've done. Instead of multiple public CDNs, we now use a single private CDN (s3 bucket + cloudfront) to serve all our artifacts. See #91
> 
> Which has improved the download speed significantly [#96 (comment)](https://github.com/privacy-scaling-explorations/snark-artifacts/pull/96#issuecomment-2182375488)

Thanks for the heads-up.  We may have to face the same issue in Zupass, though we haven't yet.  We don't much usage of our GPC artifacts yet, and the usage inside Zupass is downloaded directly from the Zupass server, so the 3rd-party CDNs will only be stressed when we get more 3rd-party devs building integrations.

I have two follow-up questions to understand what you did here and how we might need to follow it:
- Was the decision to move to S3+Cloudfront purely about performance, or was it driven by the failures mentioned in this issue?  Did you ever get a better understanding of the cause of those, or did the retries resolve them?
- Is there documentation anywhere of the specifics of your approach to the hosting side?  I see the upload code in the repo.  I haven't used S3+Cloudfront before, though I can figure it out when the time comes.

**Comment by sripwoud** [comment]
> Was the decision to move to S3+Cloudfront purely about performance, or was it driven by the failures mentioned in this issue? Did you ever get a better understanding of the cause of those, or did the retries resolve them?

both because of performance and download failures.
Download failures were because the CDN we were using (esp unpkg) were throttling requests.  
Speed was rather bad too.

 > Is there documentation anywhere of the specifics of your approach to the hosting side? I see the upload code in the repo. I haven't used S3+Cloudfront before, though I can figure it out when the time comes.
 
 Would you be interested in a IaC implementation to make that config more transparent (I am thinking terraform or pulumi). We don't use it yet. But we might. What do you think @ntampakas ?

**Comment by ntampakas** [comment]
Hey @sripwoud ,
All AWS implementations are done using IaC, more specific in Terraform. Currently, the code is in CodeCommit, but the DevOps team plans to migrate/transfer the code to GitHub.

**Comment by artwyman** [comment]
> both because of performance and download failures. Download failures were because the CDN we were using (esp unpkg) were throttling requests. Speed was rather bad too.

Do they have published limits or was it all experimentally discovered?  I'll need to decide at some point whether to prioritize this for non-Zupass users of our artifacts.

> All AWS/Infra implementations are done using IaC, more specific in Terraform/Ansible. Currently, the code is in CodeCommit, but the DevOps team plans to migrate/transfer the code to GitHub.

This sounds great.  I'll watch for this stuff to show up in GitHub (I assume in this repo?).  It may be a while before we need something similar for Zupass-related artifacts, but when that time comes it'll be helpful to see what you did here.  All my personal experience with cloud-hosting technologies was in the context of internal tools in a big company, but I'm sure I can figure out the AWS tools when I have to.

**Comment by sripwoud** [comment]
> Do they have published limits or was it all experimentally discovered? I'll need to decide at some point whether to prioritize this for non-Zupass users of our artifacts.

experimentally discovered, [here](https://github.com/semaphore-protocol/semaphore/actions/runs/9317318980/job/25647368848#step:8:134) is the recurring error we were seeing. I haven't found any docs (haven't searched very long) or detailed info about throttling in https://github.com/mjackson/unpkg/issues. But I assumed this was the reason as this error was only happening when trying to perform requests in parallel in the tests (I haven't seen errors when fetching sequentially).

> I assume in this repo?

yes, if otherwise we ll keep you informed
