### ISSUE TITLE
Update the `@zk-kit/artifacts` package and set the new CDN URL as the default one

### ISSUE THREAD

**Issue by sripwoud** [privacy-scaling-explorations/snark-artifacts#94]

**Comment by sripwoud** [comment]
@cedoor should we move on with implementing a client side solution (that we would remove when the backend solution is implemented https://github.com/privacy-scaling-explorations/snark-artifacts/issues/95)?
Or should we wait for https://github.com/privacy-scaling-explorations/snark-artifacts/issues/95 to be solved first?

**Comment by cedoor** [comment]
Looks like the "latest" URLs are working. Does it make sense to move on with them?

**Comment by sripwoud** [comment]
Based on my benchmark, using snark-artifacts.pse.dev as default downloading url would degrade performance. See https://github.com/privacy-scaling-explorations/snark-artifacts/pull/96
let's wait for Nick's feedback to see if we can improve that.
