### ISSUE TITLE
Automate updates of `https://snark-artifacts/pse.dev/project/latest` endpoint when new versions are released

### ISSUE THREAD

**Issue by sripwoud** [privacy-scaling-explorations/snark-artifacts#95]
Assuming `1.0.0-beta.1` is the latest poseidon package version,
we want 
https://snark-artifacts/pse.dev/poseidon/latest
and
https://snark-artifacts/pse.dev/poseidon/1.0.0-beta.1
to point to the same files.

Right now a cloudfront rule does the redirect, but that rule needs to be created manually everytime a new version is released.
Solutions:
- automation with terraform?
- duplicate the files? (always copy them to `project/latest` folder in the upload-artifacts workflow)?
- other?

**Comment by ntampakas** [comment]
I think the best way to do this is by using AWS CLI, manipulating the specific Cloudfront function.
I' ll start the implementation by the end of this week or the beginning of the following week.

**Comment by sripwoud** [comment]
@ntampakas have you ever used https://www.pulumi.com/ (IaC, kind of higher level alternative to terraform)
I think this could be a solution too.

**Comment by ntampakas** [comment]
> @ntampakas have you ever used https://www.pulumi.com/ (IaC, kind of higher level alternative to terraform) I think this could be a solution too.
> 
> In any case I like the idea of having the infra code version controlled. Some people are interested in seeing how you configured s3 + cloudfront. see [#65 (comment)](https://github.com/privacy-scaling-explorations/snark-artifacts/issues/65#issuecomment-2183455313)

TBH, i' ve ever used pulumi :) For CI/CD we mainly use terraform and aws cli, as it seems to work for our needs and it' s pretty flexible.
Regarding IaC version control please see my comment here: https://github.com/privacy-scaling-explorations/snark-artifacts/issues/65#issuecomment-2191289170

**Comment by ntampakas** [comment]
https://github.com/privacy-scaling-explorations/snark-artifacts/pull/114
